package com.challenges.addressbook;

import com.challenges.helpers.DisplayHelpers;
import com.challenges.helpers.ValidatorHelpers;

import java.util.ArrayList;
import java.util.function.Function;

public class AddressBook {
    static int nextId = 1;
    protected int id;
    private ArrayList<Contact> contactsList;

    public AddressBook()
    {
        id = nextId++;
        contactsList = new ArrayList<>();
    }

    public ArrayList<Contact> getContactsList() {
        return contactsList;
    }

    public void addContact(Contact contact) throws IllegalArgumentException
    {
        if (contact == null) throw new IllegalArgumentException();
        if (checkDuplicate(contact, Contact::getEmailAddress)) throw new IllegalArgumentException();
        if (checkDuplicate(contact, Contact::getPhoneNumber)) throw new IllegalArgumentException();

        contactsList.add(contact);
    }

   /* checkDuplicate initially refactored into two separate functions: checkDuplicatePhoneNumber() & checkDuplicateEmail()
   Original Code commented out
   private boolean checkDuplicateEmail(Contact contact)
    {
        for (Contact existingContact : contactsList)
        {
            if (!existingContact.getEmailAddress().isEmpty()
                    && existingContact.getEmailAddress().equals(contact.getEmailAddress())) return true;
        }
        return false;
    }

    private boolean checkDuplicatePhoneNumber(Contact contact)
    {
        for (Contact existingContact : contactsList)
        {
            if (!existingContact.getPhoneNumber().isEmpty()
                    && existingContact.getPhoneNumber().equals(contact.getPhoneNumber())) return true;
        }
        return false;
    }*/

    //The checkDuplicate function disregard empty email and phone number entries, so it doesn't count a Contact with a valid empty entry as a duplicate
    //checkDuplicate refactored by Copilot from checkDuplicateEmail and checkDuplicatePhoneNumber above
    private boolean checkDuplicate(Contact contact, Function<Contact, String> attributeGetter) {
        for (Contact existingContact : contactsList) {
            String attribute = attributeGetter.apply(existingContact);
            if (!attribute.isEmpty() && attribute.equals(attributeGetter.apply(contact))) {
                return true;
            }
        }
        return false;
    }


    public boolean removeContact(Contact contact) throws IllegalArgumentException
    {
        if (contact == null) throw new IllegalArgumentException();
        return contactsList.remove(contact);
    }

    //Just for searching by contact name - name is never allowed to be empty
    public Contact findContact(String searchCriteria) throws IllegalArgumentException
    {
        if (ValidatorHelpers.isInputNullOrEmpty(searchCriteria)) throw new IllegalArgumentException();
        for (Contact contact : contactsList) {
            if (contact.getName().equals(searchCriteria)) return contact;
        }
        return null;
    }

    //Allows searching for an empty string, as a Contact may have an empty string in phoneNumber or emailAddress
    public Contact findContact(String searchCriteria, ContactDetailType contactDetailType)
    {
        //code generated by Copilot
        if (searchCriteria == null) throw new IllegalArgumentException();
        for (Contact contact : contactsList)
        {
            switch (contactDetailType)
            {
                case PHONE_NUMBER -> {
                    if (contact.getPhoneNumber().equals(searchCriteria)) return contact;
                }
                case EMAIL_ADDRESS -> {
                    if (contact.getEmailAddress().equals(searchCriteria)) return contact;
                }
            }
        }
        return null;
    }

    public String viewAllContacts()
    {
        StringBuilder allContacts = new StringBuilder();
        for (Contact contact : contactsList)
        {
            allContacts.append(DisplayHelpers.formatContactForDisplay(contact));
        }

        return allContacts.toString();
    }
}
